### ISSUE TITLE
[feat]: UI could be better designed

### ISSUE THREAD

**Issue by Dev-Sambhav** [Dev-Sambhav/background_remover#1]
Enhanced the user interface to improve overall design look. The changes include updated color schemes, refined layout, and improved visual elements to provide a more polished and user-friendly experience.
If you want, you can also use Tailwind CSS.

**Comment by inyCation** [comment]
**#1**
can we use typescript??

**Comment by Dev-Sambhav** [comment]
> **#1** can we use typescript??

yes, you can 👍

**Comment by inyCation** [comment]
> > **#1** can we use typescript??
> 
> yes, you can 👍

Will convert the whole app with ts, after that will start on UI !! One more thing, can we use scss too??

**Comment by Dev-Sambhav** [comment]
> > > **#1** can we use typescript??
> > 
> > 
> > yes, you can 👍
> 
> Will convert the whole app with ts, after that will start on UI !! One more thing, can we use scss too??

You can convert the whole app with TS but use Tailwind CSS for the styling part

**Comment by inyCation** [comment]
hey sambhav,  
i have implemented TS, and have opened a pull request. you can review the code and let me know if we need other changes, 

live link - https://iridescent-banoffee-148d16.netlify.app/

**Comment by Dev-Sambhav** [comment]
Great job @inyCation but in future, whenever you work on any issue, create a separate branch. never change in main branch

<img width="542" alt="img" src="https://github.com/Dev-Sambhav/background_remover/assets/95364492/6c37db20-bf81-49ae-a25b-8304e6663fc8">

**Comment by Dev-Sambhav** [comment]
@inyCation This issue is still open as the UI is still not changed so you can start if you want to change.

**Comment by inyCation** [comment]
@Dev-Sambhav I'm on it , Will create a pull request as soon as I get it done.

**Comment by inyCation** [comment]
#1
hey, @Dev-Sambhav  can you review the UI and let me know if we need any changes.

link - https://relaxed-cupcake-eaeb68.netlify.app/

**Comment by Dev-Sambhav** [comment]
@inyCation, I think it will look better if we keep things in one column, also remove the navbar as currently it is a one page site or if you want to add about section then do it in the same page means create a about section and place it at the bottom of the homepage.


<img width="959" alt="image" src="https://github.com/Dev-Sambhav/background_remover/assets/95364492/50c41069-5628-466e-90a1-ac7d81c74909">

**Comment by inyCation** [comment]
#1
hey @Dev-Sambhav , i have removed the navbar, and have aligned home section in column, let me know if we need other changes. 

live -  https://relaxed-cupcake-eaeb68.netlify.app/

**Comment by Dev-Sambhav** [comment]
@inyCation Great, now open a PR so I can merge your commit. Hope you have committed all the changes in a separate branch.

Note:- Fixes: #1 must be written in the PR description so that this issue gets added to the PR.
